// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD14D1h5wGjPTEwFq371B6DUVE_ipbDKjA',
    appId: '1:636680563980:web:bc2b62dc5db5a5864bad29',
    messagingSenderId: '636680563980',
    projectId: 'dragncode-64fd3',
    authDomain: 'dragncode-64fd3.firebaseapp.com',
    storageBucket: 'dragncode-64fd3.firebasestorage.app',
    measurementId: 'G-VH4T6F24G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLfAfU1EUgz1PibM4pbc4FijtckjmC4Gs',
    appId: '1:636680563980:android:bc724408fc6cf2f84bad29',
    messagingSenderId: '636680563980',
    projectId: 'dragncode-64fd3',
    storageBucket: 'dragncode-64fd3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD14D1h5wGjPTEwFq371B6DUVE_ipbDKjA',
    appId: '1:636680563980:web:bc2b62dc5db5a5864bad29',
    messagingSenderId: '636680563980',
    projectId: 'dragncode-64fd3',
    authDomain: 'dragncode-64fd3.firebaseapp.com',
    storageBucket: 'dragncode-64fd3.firebasestorage.app',
    measurementId: 'G-VH4T6F24G0',
  );

}